### ISSUE TITLE
Add --nocdn flag to readme2tex, to support private repos and different branches

### ISSUE THREAD

**Issue by c-harding** [agurodriguez/github-texify#1]
This app does not work on private repos or other branches, because it produces rawgit.com links, which require public access to the images on the master branch. With readme2tex's --nocdn flag, this shouldn't be a problem, as GitHub itself will handle the image delivery.

**Comment by agurod42** [comment]
Hi @xsanda. Thanks for reporting the issue, I haven't had the possibility to test it on a private repo. 

I think I'm not getting what you are suggesting. When we call readme2tex in order to render TeX expressions as images we are passing --nocdn as a parameter:

https://github.com/agurodriguez/github-texify/blob/a5b703f1889ed1c8e397996e2bc6365ed04d7271/src/texify.js#L101

I'll make some tests and see if I can reproduce it. Let you know as soon as possible.

**Comment by c-harding** [comment]
My mistake: I must have misread that line and not spotted the `--nocdn` flag. However, the issue still stands, that the code is behaving as if that flag is never passed. An example of my issue: in [05-classifying-data.md](https://github.com/xsanda/SPS-notes/blob/master/05-classifying-data.md) (click on the raw view), all the links are through rawgit.com, rather than locally. If I run readme2tex locally, adding the --nocdn flag fixes this, so I'm not sure why this code doesn't. Could possibly be related to the stuff here with rawgit:
https://github.com/agurodriguez/github-texify/blob/a5b703f1889ed1c8e397996e2bc6365ed04d7271/src/texify.js#L112

**Comment by agurod42** [comment]
Got you!

The problem seems to appear because we are using rawgit in order to serve generated images with proper mimetype so GitHub renders it as an image when the README is shown. 

Take a look at: https://github.com/rgrove/rawgit/issues/44

I'm doing some research to see how this can be solved. Let you know

**Comment by c-harding** [comment]
Why are we using rawgit to serve it? Rawgit doesn't work on private repos, and I wouldn't expect a public mirror to be able to access private images. The fix seems to be to simply remove the entire try block at the link below, as GitHub is capable of resolving relative links within the same repository.
https://github.com/agurodriguez/github-texify/blob/a5b703f1889ed1c8e397996e2bc6365ed04d7271/src/texify.js#L111

**Comment by c-harding** [comment]
Never mind, I see the problem. The fix seems to be fairly simple, however. Append `?sanitize=true` to the local SVG link, instead of the two lines already in that try block:
```js
fs.writeFileSync(tmpOutputPath, fs.readFileSync(tmpOutputPath, 'utf8').replace(/\?invert_in_darkmode/g, "?invert_in_darkmode&sanitize=true"))
```

[StackOverflow](https://stackoverflow.com/a/16462143/2275559)

**Comment by c-harding** [comment]
Thank you for this!

**Comment by agurod42** [comment]
Hi @xsanda, thank you for the time and energy used in the research!

I'm just updating Heroku instance. It should be ready in a few minutes.

Have a nice day!
