### ISSUE TITLE
Only files from the most recent commit in a push are rendered

### ISSUE THREAD

**Issue by c-harding** [agurodriguez/github-texify#2]
If two commits are made before a push, only the files modified in the most recent are modified.

https://github.com/agurodriguez/github-texify/blob/a5b703f1889ed1c8e397996e2bc6365ed04d7271/src/texify.js#L41

This should be solvable by replacing the above line with:
```js
let commitFiles = [];
for (let commit of this.push.commits) {
    commitFiles.push(...commit.added, ...commit.modified);
}
```

**Comment by c-harding** [comment]
Awesome, thanks for all your work today

**Comment by xsanda** [comment]
Is the server running at the moment? I can't see any builds coming through at https://github.com/xsanda/SPS-notes/commits/master

**Comment by agurod42** [comment]
Yes, it is.

As far as I can see your request can’t be processed because we are receiving this error when trying to use Github API:
HTTP/1.1 403 Forbidden
Content-Type: application/json; charset=utf-8
Connection: close
{
  "message": "You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.",
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits"
}
https://developer.github.com/v3/#abuse-rate-limits


It’s probably because I generated a lot of request in the past hours when I was testing.

I’ll see if there is a better way to handle the requests in order to go through this limitation.

Sorry for the inconvenience

Regards,

Agustín Rodríguez
http://agurodriguez.net
